export const actionType = {
    FETCH_BRANDS_DATA: 'FETCH_BRANDS_DATA',
    FETCH_TEAMS_DATA: 'FETCH_TEAMS_DATA',
    FETCH_CPUS_DATA: 'FETCH_CPUS_DATA',
    FETCH_POSITION_DATA: 'FETCH_POSITION_DATA',
}